# Site settings
title: Kam Lasater - Thoughts and Musings
email: ckl@seekayel.com
description: >
  Thoughts and musing of Kam Lasater. All thoughts my own™
baseurl: "" 
url: "http://kamlasater.com"
twitter_username: seekayel
github_username:  seekayel

# Build settings
markdown: kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
