#!/usr/bin/env bash

# Hello! Welcome to my bootstrap script
#
# How to use:
# > bash <(curl -s https://kamlasater.com/bootstrap) | tee "bootstrap-$(date +%Y%m%d-%H%M).log"
# > ...something something
# > profit!


set -e

xcode-select --install

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

brew install git

mkdir ~/github

cd ~/github

git clone https://github.com/seekayel/laptop-install.git

echo "Now just run ./laptop-install/init.sh"
